#!/usr/bin/env node
/**
 * Crea en GitHub las 16 tareas y la épica desde .king/issues.json.
 *
 * Existe porque la escritura a GitHub estaba denegada cuando se corrió el
 * pipeline: `POST /issues` devolvía `403 Resource not accessible by integration`
 * y `git push` devolvía 403 con "Claude doesn't have GitHub access to
 * InformatiK-AI/landing-spiderman for your organization". Las cargas quedaron
 * listas para no perder el trabajo.
 *
 * Orden de creación: primero las tareas, en el orden del archivo, y la épica al
 * final. Los cuerpos citan otras tareas por número («Depende de #3») dando por
 * hecho que la tarea N es el issue #N. Si la épica se creara primero, o si el
 * repo ya tuviera issues o PRs, esa numeración se correría y los enlaces
 * apuntarían a issues equivocados. Por eso:
 *
 *   1. Cada tarea se crea con las referencias neutralizadas («tarea 3»), para
 *      no mencionar issues ajenos ni por un instante.
 *   2. Se crea la épica con la lista de tareas por su número real.
 *   3. Cada tarea se actualiza con los números reales y con «Parte de #épica».
 *
 * Uso:
 *   GITHUB_TOKEN=ghp_xxx node scripts/file-issues.mjs            # de verdad
 *   node scripts/file-issues.mjs --dry-run                       # sin escribir
 *
 * El token necesita permiso de escritura en issues del repositorio.
 */
import { readFileSync } from "node:fs";

const DRY = process.argv.includes("--dry-run");
const token = process.env.GITHUB_TOKEN;

if (!token && !DRY) {
  console.error("Falta GITHUB_TOKEN. Usa --dry-run para ver qué se crearía.");
  process.exit(1);
}

const { repo, epic, issues } = JSON.parse(readFileSync(".king/issues.json", "utf8"));
const api = `https://api.github.com/repos/${repo}/issues`;
const headers = {
  Authorization: `Bearer ${token}`,
  Accept: "application/vnd.github+json",
  "Content-Type": "application/json",
};

const FOOTER = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_";
const taskNumbers = new Set(issues.map((issue) => issue.n));

/** Reescribe cada «#N» que apunte a una tarea del archivo; deja el resto intacto. */
function renderRefs(body, render) {
  return body.replace(/#(\d+)\b/g, (match, digits) => {
    const n = Number(digits);
    return taskNumbers.has(n) ? render(n) : match;
  });
}

/** Inserta texto antes del pie de atribución, para que el pie siga siendo lo último. */
function beforeFooter(body, extra) {
  return body.endsWith(FOOTER)
    ? `${body.slice(0, -FOOTER.length)}\n\n${extra}${FOOTER}`
    : `${body}\n\n${extra}`;
}

/** En dry-run se simula la numeración de un repo sin issues ni PRs. */
let simulated = 0;

async function request(method, url, payload) {
  if (DRY) {
    return { number: method === "POST" ? ++simulated : Number(url.split("/").pop()) };
  }
  const response = await fetch(url, { method, headers, body: JSON.stringify(payload) });
  if (!response.ok) {
    throw new Error(`${method} ${url}: ${response.status} ${await response.text()}`);
  }
  return response.json();
}

const tag = DRY ? "[dry-run] " : "";
const labels = (list) => (list?.length ? `  [${list.join(", ")}]` : "");

// 1. Tareas, en orden, con las referencias neutralizadas.
const numbers = new Map();
for (const issue of issues) {
  const created = await request("POST", api, {
    title: issue.title,
    body: renderRefs(issue.body, (n) => `tarea ${n}`),
    labels: issue.labels,
  });
  numbers.set(issue.n, created.number);
  console.log(`${tag}#${created.number}  ${issue.title}${labels(issue.labels)}`);
}

// 2. Épica, con la lista de tareas por su número real.
const intro = epic.body ? `${epic.body.trim()}\n\n` : "";
const list = issues.map((issue) => `- [ ] #${numbers.get(issue.n)}`).join("\n");
const createdEpic = await request("POST", api, {
  title: epic.title,
  body: `${intro}## Tareas\n\n${list}${FOOTER}`,
  labels: epic.labels,
});
console.log(`${tag}#${createdEpic.number}  ${epic.title}${labels(epic.labels)}`);

// 3. Cada tarea, ahora con los números reales y «Parte de #épica».
for (const issue of issues) {
  await request("PATCH", `${api}/${numbers.get(issue.n)}`, {
    body: beforeFooter(
      renderRefs(issue.body, (n) => `#${numbers.get(n)}`),
      `Parte de #${createdEpic.number}.`,
    ),
  });
}
console.log(
  `${tag}${issues.length} tareas actualizadas con sus referencias reales y «Parte de #${createdEpic.number}».`,
);

const shifted = issues.find((issue) => numbers.get(issue.n) !== issue.n);
if (shifted) {
  console.log(
    `Aviso: la numeración no coincide con la de .king/tasks.md (la tarea ${shifted.n} es #${numbers.get(shifted.n)}); las referencias ya quedaron corregidas en GitHub.`,
  );
}

console.log(`\n${tag}${issues.length + 1} issues (${issues.length} tareas + 1 épica).`);
if (DRY) {
  console.log("[dry-run] Números simulados: asumen un repo sin issues ni PRs. Los reales los asigna GitHub.");
}
